### ISSUE TITLE
Last elem on mobile

### ISSUE THREAD

**Issue by pgrab86** [Tod314/tj-gallery#1]
Great work, but here is one bug. Last picture on mobile isn't have a proper size. It is visible on your demo also [https://www.jqueryscript.net/demo/Responsive-Justified-Gallery-jQuery-TJ-gallery/](https://www.jqueryscript.net/demo/Responsive-Justified-Gallery-jQuery-TJ-gallery/)

**Comment by Tod314** [comment]
Thanks for your feedback. It was fixed 
https://github.com/Tod314/tj-gallery/commit/b1e38af5a62383a181dca2df84601a4c6dbef6bf
