### ISSUE TITLE
Dynamic Data

### ISSUE THREAD

**Issue by gmum4d** [Tod314/tj-gallery#2]
Hi,  How can I apply this after dynamically loading images from a MySQL database via Ajax ?

**Comment by Tod314** [comment]
Hi, you can init gallery after ajax loaded:

`$.ajax({
	url: myurl,
	success: function(data){
		$('.gallerybox').append(data);
		$('.gallerybox').tjGallery();
	}
})`

if you want reinit, use `$('.gallerybox').tjGallery('clear');` after appending data
